# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'MerryToast' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  use_frameworks!
  pod 'Toast', '~> 3.1.0'
  # Pods for MerryToast

end
